name: New Environment
values:
  - key: baseUrl
    value: ''
  - key: adminEmail
    value: ''
  - key: adminPassword
    value: ''
  - key: userPassword
    value: ''
  - key: invalidToken
    value: ''
  - key: runId
    value: ''
  - key: emailA
    value: ''
  - key: emailB
    value: ''
